# Generated by Django 2.1.7 on 2019-04-20 11:28

import ckeditor_uploader.fields
from django.db import migrations, models
import djongo.models.fields
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=254)),
                ('author_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_on', models.DateTimeField()),
                ('comments_count', models.IntegerField(blank=True)),
                ('comments', djongo.models.fields.ArrayModelField(model_container=index.models.Comment)),
                ('likes_count', models.IntegerField(blank=True)),
                ('likes', djongo.models.fields.ArrayModelField(model_container=index.models.Like)),
            ],
        ),
    ]
