# Generated by Django 2.1.7 on 2019-04-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile_feed', '0002_user_profile_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_portfolio', models.FileField(blank=True, null=True, upload_to='profile_docs/%Y/%m/%d')),
            ],
        ),
    ]
