# Generated by Django 2.1.7 on 2019-04-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile_feed', '0004_auto_20190427_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_portfolio',
        ),
    ]
